/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Karol
 */
public class Okno extends javax.swing.JFrame {
    private Gra gra;
    /**
     * Creates new form Okno
     */
    public Okno() {
        initComponents();
    }
    
    private void Odswiez(String wiadomosc) {
        if (gra.isStan()) {
            jTextAreaWyjscie.append(wiadomosc);
            jProgressBar.setValue(gra.getRundyDoKonca());
        }
        else {
            jTextAreaWyjscie.append(wiadomosc);
            jRadioDo100.setEnabled(true);
            jRadioButtonDo1000.setEnabled(true);
            jRadioButtonDoPodanejLiczby.setEnabled(true);
            jTextFieldLiczbaZakres.setEnabled(false);

            jButtonStart.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioDo100 = new javax.swing.JRadioButton();
        jRadioButtonDo1000 = new javax.swing.JRadioButton();
        jRadioButtonDoPodanejLiczby = new javax.swing.JRadioButton();
        jTextFieldLiczbaZakres = new javax.swing.JTextField();
        jTextFieldZgadnijLiczbe = new javax.swing.JTextField();
        jLabelTwojaLiczba = new javax.swing.JLabel();
        jButtonZgadnij = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaWyjscie = new javax.swing.JTextArea();
        jProgressBar = new javax.swing.JProgressBar();
        jButtonStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRadioDo100);
        jRadioDo100.setText("Do 100");

        buttonGroup1.add(jRadioButtonDo1000);
        jRadioButtonDo1000.setText("Do 1000");

        buttonGroup1.add(jRadioButtonDoPodanejLiczby);
        jRadioButtonDoPodanejLiczby.setText("Do podaj liczbe");

        jTextFieldLiczbaZakres.setText("Podaj liczbe");

        jTextFieldZgadnijLiczbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldZgadnijLiczbeActionPerformed(evt);
            }
        });

        jLabelTwojaLiczba.setText("Twoja liczba");

        jButtonZgadnij.setText("Zgadnij");
        jButtonZgadnij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZgadnijActionPerformed(evt);
            }
        });

        jTextAreaWyjscie.setColumns(20);
        jTextAreaWyjscie.setRows(5);
        jScrollPane1.setViewportView(jTextAreaWyjscie);

        jButtonStart.setText("Start gry!");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jTextFieldZgadnijLiczbe, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonZgadnij))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jRadioDo100)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonDo1000)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonDoPodanejLiczby)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLiczbaZakres, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelTwojaLiczba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonStart))
                    .addComponent(jProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioDo100)
                    .addComponent(jRadioButtonDo1000)
                    .addComponent(jRadioButtonDoPodanejLiczby)
                    .addComponent(jTextFieldLiczbaZakres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTwojaLiczba)
                    .addComponent(jButtonStart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldZgadnijLiczbe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonZgadnij))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldZgadnijLiczbeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldZgadnijLiczbeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldZgadnijLiczbeActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        if(jRadioDo100.isSelected())
            gra = new Gra(100);
        else if(jRadioButtonDo1000.isSelected())
            gra = new Gra (1000);
        else if(jRadioButtonDoPodanejLiczby.isSelected()) {
            gra = new Gra (Integer.parseInt(jTextFieldLiczbaZakres.getText()));
        }
        
        jRadioDo100.setEnabled(false);
        jRadioButtonDo1000.setEnabled(false);
        jRadioButtonDoPodanejLiczby.setEnabled(false);
        jTextFieldLiczbaZakres.setEnabled(false);
        
        jButtonStart.setEnabled(false);
        
        jProgressBar.setMaximum(gra.getRundyDoKonca());
        jProgressBar.setValue(gra.getRundyDoKonca());
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonZgadnijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZgadnijActionPerformed
        Odswiez(gra.Runda(Integer.parseInt(jTextFieldZgadnijLiczbe.getText())));
    }//GEN-LAST:event_jButtonZgadnijActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Okno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonZgadnij;
    private javax.swing.JLabel jLabelTwojaLiczba;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JRadioButton jRadioButtonDo1000;
    private javax.swing.JRadioButton jRadioButtonDoPodanejLiczby;
    private javax.swing.JRadioButton jRadioDo100;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaWyjscie;
    private javax.swing.JTextField jTextFieldLiczbaZakres;
    private javax.swing.JTextField jTextFieldZgadnijLiczbe;
    // End of variables declaration//GEN-END:variables
}
